---
replicaCount: 2
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: latest
connectors_with_custom_templates:
- request_path: /prometheus-msteams
  template_file: ./default-message-card.tmpl
  webhook_url: "https://outlook.office.com/webhook/40d590e3-a4c5-47ec-8391-f95ff4cdd428@5f2f4ea8-f1ba-4234-898c-c4ae4a4c70bb/IncomingWebhook/e670403ba775418aa20ddf4a8705308b/b003c2cf-83af-4028-acb6-86f1b05a8e51"
  escape_underscores: true # get the effect of -auto-escape-underscores.
- request_path: /prometheus-alerts
  template_file: ./default-message-card.tmpl
  webhook_url: "https://outlook.office.com/webhook/f56da971-2c68-436c-864f-178d5e623dd2@5f2f4ea8-f1ba-4234-898c-c4ae4a4c70bb/IncomingWebhook/8969cbcd2fb1494c9d861bcc019ffe21/b003c2cf-83af-4028-acb6-86f1b05a8e51"
  escape_underscores: true # get the effect of -auto-escape-underscores.
- request_path: /Solarwinds
  template_file: ./default-message-card.tmpl
  webhook_url: "https://outlook.office.com/webhook/293729ae-34f9-4995-97c3-deb3b867af42@5f2f4ea8-f1ba-4234-898c-c4ae4a4c70bb/IncomingWebhook/cbdccf1e00f84e02bfca476110f88454/e9517f7e-8c30-45b0-b64f-03495ce7c56d"
  escape_underscores: true # get the effect of -auto-escape-underscores.
service:
  type: NodePort
  port: 2000
  nodePort: 34555

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: ops # change this accordingly
    scrapeInterval: 30s

